/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: {
            50: 'var(--brand-primary-50)',
            100: 'var(--brand-primary-100)',
            200: 'var(--brand-primary-200)',
            300: 'var(--brand-primary-300)',
            400: 'var(--brand-primary-400)',
            500: 'var(--brand-primary-500)',
            600: 'var(--brand-primary-600)',
            700: 'var(--brand-primary-700)',
            800: 'var(--brand-primary-800)',
            900: 'var(--brand-primary-900)',
            950: 'var(--brand-primary-950)',
            DEFAULT: 'var(--brand-primary-500)',
          },
          accent: {
            50: 'var(--brand-accent-50)',
            100: 'var(--brand-accent-100)',
            200: 'var(--brand-accent-200)',
            300: 'var(--brand-accent-300)',
            400: 'var(--brand-accent-400)',
            500: 'var(--brand-accent-500)',
            600: 'var(--brand-accent-600)',
            700: 'var(--brand-accent-700)',
            800: 'var(--brand-accent-800)',
            900: 'var(--brand-accent-900)',
            DEFAULT: 'var(--brand-accent-500)',
          },
        },
        personality: {
          analyst: 'var(--personality-analyst)',
          diplomat: 'var(--personality-diplomat)',
          sentinel: 'var(--personality-sentinel)',
          explorer: 'var(--personality-explorer)',
        },
        mbti: {
          'ei-energy': 'var(--mbti-ei-energy)',
          'ei-introvert': 'var(--mbti-ei-introvert)',
          'sn-sensing': 'var(--mbti-sn-sensing)',
          'sn-intuition': 'var(--mbti-sn-intuition)',
          'tf-thinking': 'var(--mbti-tf-thinking)',
          'tf-feeling': 'var(--mbti-tf-feeling)',
          'jp-judging': 'var(--mbti-jp-judging)',
          'jp-perceiving': 'var(--mbti-jp-perceiving)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          DEFAULT: 'var(--color-success-500)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          DEFAULT: 'var(--color-warning-500)',
        },
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
          DEFAULT: 'var(--color-error-500)',
        },
        info: {
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          800: 'var(--color-info-800)',
          900: 'var(--color-info-900)',
          DEFAULT: 'var(--color-info-500)',
        },
      },
      fontFamily: {
        display: 'var(--font-family-display)',
        sans: 'var(--font-family-sans)',
        serif: 'var(--font-family-serif)',
        mono: 'var(--font-family-mono)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        base: 'var(--radius-base)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        '4xl': 'var(--radius-4xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        primary: 'var(--shadow-primary)',
        accent: 'var(--shadow-accent)',
        success: 'var(--shadow-success)',
        error: 'var(--shadow-error)',
        ring: 'var(--shadow-ring)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
        slower: '700ms',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeUp: 'fadeUp var(--duration-slow) var(--ease-spring) both',
      },
    },
  },
  plugins: [],
};